import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="py-6 bg-black justify-items-center"><h1 className="text-5xl text-white">My Site</h1></div>
        <nav className="grid grid-cols-3 justify-items-center">
          <Link className="w-full py-3 bg-red-500 text-2xl text-center" href="/">Home</Link>
          <Link className="w-full py-3 bg-yellow-300 text-2xl text-center" href="/about">About</Link>
          <Link className="w-full py-3 bg-emerald-400 text-2xl text-center" href="/login">Login</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
